#!/bin/bash

set -e

export API_PORT=8081 API_PROTOCOL=http API_DOMAIN=localhost ADDRESS=0.0.0.0
echo "[.] starting backend."
node backend/dev.js &
BACKEND_PID=$!
echo "[.] starting frontend"
node dev.js &
FRONTEND_PID=$!

function finish {
    kill $BACKEND_PID $FRONTEND_PID 2>/dev/null
}
trap finish EXIT


while true; do
    sleep 2
    # if either of them is dead, exit with 1.
    if ! kill -0 $FRONTEND_PID 2>/dev/null; then
	echo "[x] frontend is dead?"
	exit 1;v
    fi
    if ! kill -0 $BACKEND_PID 2>/dev/null; then
	echo "[x] backend is dead?"
	exit 1;
    fi
done

